name: Upgrade npm packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 4'

jobs:
  test:
    name: Upgrade npm packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'yarn'

      - name: Install node-gyp
        run: npm install -g node-gyp

      - name: Upgrade packgaes
        run: yarn upgrade --latest

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CP_APP_ID }}
          private_key: ${{ secrets.CP_APP_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: '[自動] 依存関係の更新'
          commit-message: '[自動] 依存関係の更新'
          labels: 'dependencies'
          branch: create-pull-request/upgrade-npm-packages
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
